// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axmvltymzmupjqtocrfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4bXZsdHltem11cGpxdG9jcmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjcxNDksImV4cCI6MjA3MTU0MzE0OX0.hzYTqjWDZcxolr139trxwy-rKLcKoJgKFftLOo9BDxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});